Nome:  Grande APK

Vamos.:
  Fluxo de trabalho_dispatch  :

Empregos:
 Construir  :
  Corrida   :   Ubuntu-último

  Passos  :
       -  Nome:  Baixar projeto
 Usos   :   C.

                           :                                                                                                                                                                     :             
 :c.|     :     :                   
                         mkdir projeto               
 unzip -o TAXI_SC_ANDROID_ALARME_V13.zip -d projetoTAXI_SC_ANDROID_ALARME_.zip -d projeto1.zip -d projetoTAXI_SC_ANDROID_ALARME_.zip -d projeto13.zip -d projetoTAXI_SC_ANDROID_ALARME_.zip -d projeto1.zip -d projetoTAXI_SC_ANDROID_ALARME_.zip -d projeto 

Eu.
   :    :                          EUE. Eu.  UE. Eu.   U. UE.  :  Com... ações/setup-java@v4
 A.        :
  Distribuição  :   Temurin
 Java-versão  :   '17'

      - Nome   :     Configurar Gradle
Configurar Gradle
  Com...   :     :
  Versão de Gradle   :  '8.9'  :  '8.9'

    -    : APK semelhante :  APK semelhante
  Corra! :  gradle -p projeto assembleDebug :  gradle -p projeto assembleDebug

    -    : Disponibilizar APK :  APK disponível
 Usos :  Ações/Upload-Artifact@v4 :  ações/upload-artifact@v4
 Com...  :    :
 Nome  : TAXI-SC-TESTE-APK : TAXI-SC-TESTE-APK
          path: projeto/app/build/outputs/apk/debug/app-debug.apk
